M48
; DRILL file {KiCad (6.0.7-1)-1} date Sunday, March 19, 2023 at 01:44:48 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-19T13:44:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1250
%
G90
G05
T1
X4.3499Y-3.6862
X4.3499Y-3.9138
T2
X4.65Y-5.2
X4.7Y-3.3
X6.7Y-3.9
X6.7Y-5.0
T0
M30
